spring:
  application:
    name: commerce-event-sourced-promotion-voucher-campaign
  threads:
    virtual:
      enabled: true
  datasource:
    hikari:
      maximum-pool-size: 20
      connection-timeout: 250
      data-source-properties:
        options: "-c lock_timeout=500ms -c statement_timeout=3s"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

voucher:
  projection:
    worker:
      enabled: true
