spring:
  datasource:
    url: ${SHIFT_COVERAGE_DATABASE_URL:jdbc:postgresql://localhost:5432/shift_coverage}
    username: ${SHIFT_COVERAGE_DATABASE_USERNAME:shift_coverage}
    password: ${SHIFT_COVERAGE_DATABASE_PASSWORD:shift_coverage}
    hikari:
      maximum-pool-size: 8
