package io.bluetape4k.workshop.optimization.warehouseallocation.planner

internal typealias WarehouseAllocationPlannerOutput = io.bluetape4k.workshop.optimization.warehouseallocation.domain.WarehouseAllocationPlannerOutput
