package io.bluetape4k.workshop.optimization.warehouseallocation.planner

internal typealias WarehouseAllocationPlannerInput = io.bluetape4k.workshop.optimization.warehouseallocation.domain.WarehouseAllocationPlannerInput
