spring:
    application:
        name: ProtobufJsonMvcApplication
    info:
        build:
            encoding: UTF-8

    profiles:
        active: cbor

    aot:
        enabled: true  # AOT (Ahead Of Time) 컴파일 활성화
