spring:
    application:
        name: sample-spring-modulith

    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
        driver-class-name: org.h2.Driver
        username: sa
        password:
        hikari:
            driver-class-name: org.h2.Driver
            maximum-pool-size: 100

management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: "*"
