spring:
    application:
        name: sample-spring-modulith

management:
    tracing:
        sampling:
            probability: 1.0
    endpoints:
        web:
            exposure:
                include: "*"
