spring:
    cloud:
        aws:
            endpoint: ${AWS_ENDPOINT_URL:${testcontainers.floci.aws-endpoint:http://localhost:4566}}
            region:
                static: us-east-1
            credentials:
                access-key: noop
                secret-key: noop
