package io.bluetape4k.workshop.imageprocessing.advanced.persistence

import io.bluetape4k.codec.Base58
import io.bluetape4k.logging.KLogging
import io.bluetape4k.support.requireNotNull
import io.bluetape4k.testcontainers.database.PostgreSQLServer
import io.bluetape4k.workshop.imageprocessing.advanced.model.AssetMetadataInput
import io.bluetape4k.workshop.imageprocessing.advanced.model.ImageDimensions
import io.bluetape4k.workshop.imageprocessing.advanced.model.ImageObjectInput
import io.bluetape4k.workshop.imageprocessing.advanced.model.ImageObjectKind
import org.junit.jupiter.api.TestInstance
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.test.context.ActiveProfiles
import org.springframework.test.context.DynamicPropertyRegistry
import org.springframework.test.context.DynamicPropertySource

/**
 * Abstract base class for image persistence integration tests.
 *
 * Provides a shared PostgreSQL container via [PostgreSQLServer.Launcher.postgres]
 * and convenience builder methods for test data.
 *
 * ## Behavior / Contract
 * - Parallel test execution is disabled (see junit-platform.properties).
 * - Each test method must use a unique checksum to avoid cross-test contamination,
 *   because [ImagePersistenceService] uses PROPAGATION_REQUIRES_NEW and commits
 *   independently of any outer transaction — `@Rollback` would not work here.
 */
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.NONE)
@ActiveProfiles("test")
@TestInstance(TestInstance.Lifecycle.PER_CLASS)
abstract class AbstractImagePersistenceTest {

    companion object : KLogging() {

        val postgres = PostgreSQLServer.Launcher.postgres

        @JvmStatic
        @DynamicPropertySource
        fun postgresProperties(registry: DynamicPropertyRegistry) {
            registry.add("spring.datasource.url") { postgres.jdbcUrl }
            registry.add("spring.datasource.username") { postgres.username.requireNotNull("postgres.username") }
            registry.add("spring.datasource.password") { postgres.password.requireNotNull("postgres.password") }
        }
    }

    /**
     * Builds an [AssetMetadataInput] with sensible defaults.
     *
     * A unique [checksum] is generated by default so callers that do not supply
     * one get test isolation for free.
     */
    protected fun buildMetadata(
        checksum: String = "sha256-${Base58.randomString(12)}",
        filename: String? = "test.jpg",
        contentType: String? = "image/jpeg",
        byteSize: Long? = 12_345L,
        dimensions: ImageDimensions? = ImageDimensions(800, 600),
    ): AssetMetadataInput = AssetMetadataInput(
        checksum = checksum,
        originalFilename = filename,
        contentType = contentType,
        byteSize = byteSize,
        dimensions = dimensions,
    )

    /**
     * Builds a list of [ImageObjectInput] containing one ORIGINAL and one VARIANT entry,
     * suitable for passing to [ImagePersistenceService.recordJobSuccess].
     */
    protected fun buildObjects(assetId: Long): List<ImageObjectInput> = listOf(
        ImageObjectInput(
            kind = ImageObjectKind.ORIGINAL,
            variantName = null,
            s3Key = "uploads/${assetId}/original.jpg",
            publicUrl = "https://cdn.example.com/uploads/${assetId}/original.jpg",
            width = 800,
            height = 600,
            byteSize = 12_345L,
            format = "jpeg",
        ),
        ImageObjectInput(
            kind = ImageObjectKind.VARIANT,
            variantName = "thumbnail",
            s3Key = "uploads/${assetId}/thumbnail.jpg",
            publicUrl = "https://cdn.example.com/uploads/${assetId}/thumbnail.jpg",
            width = 200,
            height = 150,
            byteSize = 2_048L,
            format = "jpeg",
        ),
    )
}
