spring:
    application:
        name: Customers
    aot:
        enabled: true  # AOT (Ahead Of Time) 컴파일 활성화

server:
    port: 8081

management:
    endpoints:
        web:
            exposure:
                include: "*"
