spring:
    application:
        name: kotlin-gatling-app

    profiles:
        default: "dev"

    jackson:
        serialization:
            indent-output: true
    lifecycle:
        timeout-per-shutdown-phase: 10s     # Graceful Shutdown 시간

    threads:
        virtual:
            enabled: true   # Virtual Thread 사용 여부

server:
    tomcat:
        threads:
            max: 16
            min-spare: 2

    shutdown: graceful  # WebServer Graceful shutdown (https://www.baeldung.com/spring-boot-web-server-shutdown)

# Build Info
info:
    name: ${spring.application.name}
    description: Kotlin Gatling Demo
    environment: ${spring.profiles.active}
    version: 0.1.0

# swagger-ui custom path
springdoc:
    swagger-ui:
        path: /swagger-ui.html
