spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exposedmvcjdbc
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    io.bluetape4k: DEBUG
    org.jetbrains.exposed: INFO
    org.springframework: WARN
