-- CASE_INSENSITIVE_IDENTIFIERS=TRUE is set in the R2DBC URL so that:
--   • @Table("users") → "users" in generated SQL matches table USERS (H2 stores unquoted as uppercase)
--   • Spring Data R2DBC H2 dialect quoted columns "ID","NAME",… match unquoted id,name,…
--   • Custom @Query using u.email (lowercase) matches column email/EMAIL
CREATE TABLE IF NOT EXISTS users
(
    id     INT GENERATED BY DEFAULT AS IDENTITY,
    name   VARCHAR(255) NOT NULL,
    login  VARCHAR(255) NOT NULL,
    email  VARCHAR(255) NOT NULL,
    avatar VARCHAR(255),
    PRIMARY KEY (id)
);
